src/main/java/com/jamjam/bookjeok/domains/member/entity/Follow.java, src/main/java/com/jamjam/bookjeok/domains/member/entity/Member.java, src/main/java/com/jamjam/bookjeok/domains/member/entity/MemberRole.java
member엔티티와 follow 엔터티 생성 및 필드값 생성 완료
=> feat: member엔터티와 follow 엔터티 생성

src/main/java/com/jamjam/bookjeok/domains/community/entity/Bookmark.java, src/main/java/com/jamjam/bookjeok/domains/community/entity/Comment.java, src/main/java/com/jamjam/bookjeok/domains/community/entity/Like.java, src/main/java/com/jamjam/bookjeok/domains/community/entity/Post.java, src/main/java/com/jamjam/bookjeok/domains/community/entity/Report.java
=> [FEAT] 커뮤니티 엔티티 생성

src/main/java/com/jamjam/bookjeok/domains/book/entity/Author.java, src/main/java/com/jamjam/bookjeok/domains/book/entity/Book.java, src/main/java/com/jamjam/bookjeok/domains/book/entity/BookAuthor.java, src/main/java/com/jamjam/bookjeok/domains/book/entity/BookCategory.java, src/main/java/com/jamjam/bookjeok/domains/book/entity/Publisher.java, src/main/java/com/jamjam/bookjeok/domains/book/entity/Review.java, src/main/java/com/jamjam/bookjeok/domains/book/entity/StockNotification.java, src/main/java/com/jamjam/bookjeok/domains/notice/entity/Notice.java, src/main/java/com/jamjam/bookjeok/domains/question/entity/Question.java, src/main/java/com/jamjam/bookjeok/domains/question/entity/QuestionCategory.java
=> [FEAT] 도서 , CS 관련 Entity 생성

src/main/resources/application.yml, src/test/resources/application-test.yml
show_sql 옵션 추가
application-test.yml애 mybatis type-aliases-package 옵션 추가
=> feat: 애플리케이션 설정 파일에 show_sql 옵션 추가

build.gradle, src/main/java/com/jamjam/bookjeok/domains/book/contoller/BookApiController.java, src/main/java/com/jamjam/bookjeok/domains/book/dto/BookApiDTO.java, src/main/java/com/jamjam/bookjeok/domains/book/dto/BookDTO.java, src/main/java/com/jamjam/bookjeok/domains/book/dto/NaverResultDTO.java, src/main/java/com/jamjam/bookjeok/domains/book/repository/BookRepository.java, src/main/java/com/jamjam/bookjeok/domains/book/service/BookApiService.java, src/main/java/com/jamjam/bookjeok/domains/book/service/BookCommandService.java
=> [FEAT] 도서 정보 연동 API 구현

src/main/java/com/jamjam/bookjeok/domains/coupon/entity/Coupon.java, src/main/java/com/jamjam/bookjeok/domains/coupon/entity/CouponBox.java, src/main/java/com/jamjam/bookjeok/domains/coupon/entity/DiscountType.java, src/main/java/com/jamjam/bookjeok/domains/order/entity/DeliveryAddress.java, src/main/java/com/jamjam/bookjeok/domains/point/entity/Point.java, src/main/java/com/jamjam/bookjeok/domains/point/entity/PointType.java, src/test/resources/application-test.yml
#38 
**1. Coupon, CouponBox, DeliveryAddress, Point** 
연관 관계 객체->FK컬럼으로 변경, 아이디 이름 id -> 구체적인 id로 수정
**2. Coupon 클래스에 테이블 수정 사항 반영**
- discount_type, discount_value, min_order_amount, max_discount_amount 컬럼 추가
- DiscountType Enum 파일 추가
**3. CouponBox 클래스에 테이블 수정 사항 반영**
- order_uid 컬럼 제약사항 변경: not null -> null 허용 
**4. Point 클래스에 테이블 수정 사항 반영**
- save_status 컬럼 삭제, point_type 추가 
- PointType Enum 파일 추가 
**5. DeliveryAddress 클래스에 테이블 수정 사항 반영**
-  postal_code 컬럼 데이터타입 변경: int -> VARCHAR(10)
=> [REFACTOR] 쿠폰, 포인트, 배송 관련 엔티티 수정

src/main/java/com/jamjam/bookjeok/domains/community/entity/Bookmark.java, src/main/java/com/jamjam/bookjeok/domains/community/entity/Comment.java, src/main/java/com/jamjam/bookjeok/domains/community/entity/Like.java, src/main/java/com/jamjam/bookjeok/domains/community/entity/Post.java, src/main/java/com/jamjam/bookjeok/domains/community/entity/Report.java
커뮤니티 게시글, 댓글, 즐겨찾기, 좋아요, 신고 기능 엔티티 연관관계 제거 및 아이디명 변경 #38
=> [REFACTOR] 커뮤니티 게시글, 댓글, 즐겨찾기, 좋아요, 신고 기능 엔티티 연관관계 제거 및 아이디명 변경

src/main/java/com/jamjam/bookjeok/domains/book/entity/Book.java, src/main/java/com/jamjam/bookjeok/domains/book/entity/BookAuthor.java, src/main/java/com/jamjam/bookjeok/domains/book/entity/Review.java, src/main/java/com/jamjam/bookjeok/domains/book/entity/StockNotification.java, src/main/java/com/jamjam/bookjeok/domains/notice/entity/Notice.java, src/main/java/com/jamjam/bookjeok/domains/question/entity/Question.java, src/main/java/com/jamjam/bookjeok/domains/question/entity/QuestionAnswer.java
Book, BookAuthor, Notice, Question, QuestionAnswer, Review StockNotification Entity 제약조건 삭제 및 연관관계 수정, 객체 참조에서 ID값 참조로 변경 (#38)
=> [REFACTOR]: 도서, 공지사항, 문의사항 엔터티 연관관계 및 제약조건 수정

src/main/java/com/jamjam/bookjeok/domains/book/entity/BookAuthor.java
=> [FIX] BookAuthor 오류 수정

src/main/resources/application.yml, src/test/resources/application-test.yml
- application.yml
- datasource 관련 환경변수명을 LOCAL_ 접두사에서 SPRING_LOCAL_ 접두사로 변경
- 서버 포트 설정을 하드코딩된 8080에서 SERVER_PORT 환경변수로 변경
- application-test.yml
- h2 db에서 mariadb로 변경
=> [REFACTOR] 환경변수 키 이름 및 서버 포트 설정 방식 변경

build.gradle
dependencies에 testAnnotationProcessor 'org.projectlombok:lombok' 추가
=> [CHORE] 테스트 클래스에서 롬복을 사용할 수 있도록 build.gradle에 추가

src/main/java/com/jamjam/bookjeok/domains/order/service/cart/CartServiceImpl.java, src/test/java/com/jamjam/bookjeok/domains/order/controller/cart/CartControllerTest.java, src/test/java/com/jamjam/bookjeok/domains/order/service/cart/CartServiceImplTest.java
"장바구니에 해당 도서 정보가 없습니다." 으로 예외 메시지 변경
=> [REFACTOR] CartBookNotFoundException 예외 메시지 변경

src/main/java/com/jamjam/bookjeok/domains/book/entity/Book.java, src/main/java/com/jamjam/bookjeok/domains/book/entity/BookAuthor.java
**도서 테이블 및 도서-저자 테이블 데이터 저장을 위한 엔터티 수정**
- BookEntity : `@Builder` bookInfo 추가
- BoookAuthorEntity : `@Builder` 생성
=> [FEAT] Book Entity, BookAuthor Entity 변경

src/main/java/com/jamjam/bookjeok/domains/order/controller/cart/CartController.java, src/main/java/com/jamjam/bookjeok/domains/order/dto/cart/request/CartMemberIdRequest.java, src/main/java/com/jamjam/bookjeok/domains/order/dto/cart/response/CartBookListResponse.java, src/main/java/com/jamjam/bookjeok/domains/order/dto/cart/response/CartBookResponse.java, src/main/java/com/jamjam/bookjeok/domains/order/repository/cart/mapper/CartMapper.java, src/main/java/com/jamjam/bookjeok/domains/order/service/cart/CartService.java, src/main/java/com/jamjam/bookjeok/domains/order/service/cart/CartServiceImpl.java, src/main/resources/mappers/domain/order/cart/CartMapper.xml, src/test/java/com/jamjam/bookjeok/domains/order/controller/cart/CartControllerTest.java, src/test/java/com/jamjam/bookjeok/domains/order/repository/cart/mapper/CartMapperTest.java, src/test/java/com/jamjam/bookjeok/domains/order/service/cart/CartServiceImplTest.java
장바구니 기능 구현 (#29)
- 장바구니에 있는 도서 정보를 조회하는 기능 구현
- 회원uid로 장바구니에 있는 모든 도서 정보를 조회한다.
=> [FEATURE] memberUid로 장바구니에 있는 도서 정보를 조회하는 기능 구현

src/main/java/com/jamjam/bookjeok/domains/order/entity/OrderDetail.java
- OrderDetail 엔티티 필드명 수정, 수정일시 필드명 추가
=> [FEATURE] OrderDetail 엔티티 수정

build.gradle
✅ FileStorageService 파일 및 디렉토리 입출력 컨트롤을 위한 라이브러리 추가
=> [BUILD] Apache Commons IO 라이브러리 추가

src/main/java/com/jamjam/bookjeok/domains/member/dto/response/FollowDTO.java, src/main/resources/mappers/member/FollowMapper.xml
- FollowDTO 에서 Builder import 삭제하기
- FollowMapper에서 follower_id를 follower_uid로 수정/ following_id를 following_uid로 수정
=> [REFACTOR] Builder import 및 mapper에서 컬럼명 수정

src/main/java/com/jamjam/bookjeok/domains/member/controller/InterestAuthorController.java, src/main/java/com/jamjam/bookjeok/domains/member/dto/BookNameDTO.java, src/main/java/com/jamjam/bookjeok/domains/member/dto/InterestAuthorDTO.java, src/main/java/com/jamjam/bookjeok/domains/member/dto/response/InterestAuthorDTO.java, src/main/java/com/jamjam/bookjeok/domains/member/repository/mapper/InterestAuthorMapper.java, src/main/java/com/jamjam/bookjeok/domains/member/service/InterestAuthorService.java, src/main/resources/mappers/member/InterestAuthorMapper.xml, src/test/java/com/jamjam/bookjeok/domains/member/controller/InterestAuthorControllerTest.java, src/test/java/com/jamjam/bookjeok/domains/member/repository/mapper/InterestAuthorMapperTest.java, src/test/java/com/jamjam/bookjeok/domains/member/service/InterestAuthorServiceTest.java
✅ 특정 회원이 즐겨찾기 한 작가와 그 작가의 책 목록 가져오기
- 즐겨찾기 한 작가 목록 조회 mapper 만들기
- 작가의 목록과 그 작가의 책 정보 가져오기  
- 테스트 하기 
- 즐겨찾기 한 작가목록 조회 service 만들기
- 테스트 하기 
- 즐겨찾기 한 작가목록 조회 controller 만들기
- 테스트 하기
=> [FEAT] 특정 회원의 관심 작가와 그 작가의 책 목록 가져오기

src/main/java/com/jamjam/bookjeok/domains/order/dto/cart/request/CartRequest.java, src/main/java/com/jamjam/bookjeok/domains/order/repository/cart/mapper/CartMapper.java, src/main/java/com/jamjam/bookjeok/domains/order/service/cart/CartServiceImpl.java, src/main/resources/mappers/domain/order/cart/CartMapper.xml, src/test/java/com/jamjam/bookjeok/domains/order/controller/cart/CartControllerTest.java, src/test/java/com/jamjam/bookjeok/domains/order/repository/cart/mapper/CartMapperTest.java, src/test/java/com/jamjam/bookjeok/domains/order/service/cart/CartServiceImplTest.java
books 테이블에 존재하는 도서 정보인지 검증하는 로직에서 도서 가격을 가져와서 사용하도록 코드를 수정
=> [REFACTOR] 클라이언트가 서버에 도서 가격을 전달하지 않도록 코드 수정

src/main/java/com/jamjam/bookjeok/domains/book/controller/BookApiController.java, src/main/java/com/jamjam/bookjeok/domains/book/dto/BookCategoryDTO.java, src/main/java/com/jamjam/bookjeok/domains/book/dto/BookDTO.java
=> [CHORE] books.controller 패키지명 변경

src/main/java/com/jamjam/bookjeok/domains/book/service/BookApiServiceImpl.java
✅ **API 데이터 저장 메소드 분리 및 카테고리 저장 값 변경**
- find** 로직 내부에서 처리하던 save** 로직 메소드 분리
- 카테고리 save 시 modified_at null 로 변경
=> [REFACTOR] API 데이터 저장 메소드 분리 및 카테고리 저장 값 변경

src/main/java/com/jamjam/bookjeok/common/service/FileStorageService.java, src/main/java/com/jamjam/bookjeok/domains/book/controller/BookAdminController.java, src/main/java/com/jamjam/bookjeok/domains/book/dto/BookDetailDTO.java, src/main/java/com/jamjam/bookjeok/domains/book/dto/request/BookCategoryModifyRequest.java, src/main/java/com/jamjam/bookjeok/domains/book/dto/request/BookCategoryRequest.java, src/main/java/com/jamjam/bookjeok/domains/book/dto/request/BookRequest.java, src/main/java/com/jamjam/bookjeok/domains/book/dto/response/BookCategoryResponse.java, src/main/java/com/jamjam/bookjeok/domains/book/dto/response/BookResponse.java, src/main/java/com/jamjam/bookjeok/domains/book/entity/Book.java, src/main/java/com/jamjam/bookjeok/domains/book/entity/BookCategory.java, src/main/java/com/jamjam/bookjeok/domains/book/repository/mapper/BookMapper.java, src/main/java/com/jamjam/bookjeok/domains/book/service/BookAdminService.java, src/main/java/com/jamjam/bookjeok/domains/book/service/BookAdminServiceImpl.java, src/main/java/com/jamjam/bookjeok/exception/book/BookCategoryNotFoundException.java, src/main/java/com/jamjam/bookjeok/exception/book/BookErrorCode.java, src/main/java/com/jamjam/bookjeok/exception/book/BookExceptionHandler.java, src/main/java/com/jamjam/bookjeok/exception/book/RegistPreexistingBookException.java, src/main/java/com/jamjam/bookjeok/exception/book/RegistPreexistingCategoryException.java, src/main/resources/mappers/book/BookMapper.xml, src/test/java/com/jamjam/bookjeok/domains/book/controller/BookAdminControllerTest.java, src/test/java/com/jamjam/bookjeok/domains/book/mapper/BookMapperTest.java, src/test/java/com/jamjam/bookjeok/domains/book/service/BookAdminServiceImplTest.java
**관리자 도서 등록, 수정, 삭제, 조회 기능 개발**  
✅ 관리자 domain에서 도서 정보 등록, 수정, 삭제, 조회
- 도서 정보 저장
- 도서 정보 수정
- 도서 수량 수정
- 도서 삭제
- 도서 최신순 / 관심 도서 많은 순 / 판매량 많은 순 조회
- 도서 제목 / 작가 / 출판사 별 조회
- 도서 상세 조회
✅ 도서 관리 예외 상황 컨트롤
- BookNotFoundException
- 존재하지 않는 도서의 ID / ISBN 번호로 도서를 조회할 경우 
- BookNotFoundCategoryException
- 존재하지 않는 카테고리의 이름을 조회할 경우
- RegistPreeixtingBookException
- 이미 존재하는 도서 정보를 등록하려고 할 경우
- RegistPreexistingCategoryException
- 이미 존재하는 카테고리 정보를 등록하려고 할 경우 
✅ 관리자 도서 비즈니스 로직 처리 테스트 완료
- BookAdminController
- 컨트롤러 호출을 통한 도서 관리 비즈니스 로직 처리 테스트 
- 예외 처리 테스트 
- BookAdminServiceImpl 
- 관리자 도메인의 도서 관리 비즈니스 로직 처리 테스트 
- 예외 처리 테스트 
- BookMapper
- keyword 별 / 정렬 조건 별 도서 조회 
- 도서 상세 정보 조회
- 도서 카테고리 정보 조회
=> [FEATURE] 관리자 도서 등록, 수정, 삭제, 조회 기능 개발

src/main/java/com/jamjam/bookjeok/domains/member/controller/InterestAuthorController.java, src/main/java/com/jamjam/bookjeok/domains/member/dto/request/InterestAuthorRequest.java, src/main/java/com/jamjam/bookjeok/domains/member/repository/repository/InterestAuthorRepository.java, src/main/java/com/jamjam/bookjeok/domains/member/service/InterestAuthorService.java, src/main/java/com/jamjam/bookjeok/exception/member/MemberErrorCode.java, src/test/java/com/jamjam/bookjeok/domains/member/controller/InterestAuthorControllerTest.java, src/test/java/com/jamjam/bookjeok/domains/member/repository/mapper/InterestAuthorMapperTest.java, src/test/java/com/jamjam/bookjeok/domains/member/service/InterestAuthorServiceTest.java
✅ 관심 작가 삭제 기능 구현
: 관심 작가가 목록에 등록 되어 있는 경우에 삭제 하기
- 관심 작가 삭제 Controller 작성
- 관심 작가 삭제 Controller 테스트
- 관심 작가 삭제 Service 작성
- 관심 작가 삭제 Service 테스트
- 관심 작가 삭제 Repository작성
- 관심 작가 삭제 실패 시 예외 처리
- 리스트에 등록되어 있지 않는 작가 예외 처리
- 에러 코드 작성
=> [FEATURE] 관심 작가 삭제 기능 구현

src/main/java/com/jamjam/bookjeok/domains/order/controller/order/PendingOrderController.java, src/main/java/com/jamjam/bookjeok/domains/order/dto/pendingorder/request/PendingOrderBookItemsRequest.java, src/main/java/com/jamjam/bookjeok/domains/order/dto/pendingorder/request/PendingOrderRequest.java, src/main/java/com/jamjam/bookjeok/domains/order/dto/pendingorder/response/PendingOrderResponse.java, src/main/java/com/jamjam/bookjeok/domains/order/entity/PendingOrder.java, src/main/java/com/jamjam/bookjeok/domains/order/repository/order/pendingorder/PendingOrderRepository.java, src/main/java/com/jamjam/bookjeok/domains/order/service/pendingorder/PendingOrderService.java, src/main/java/com/jamjam/bookjeok/domains/order/service/pendingorder/PendingOrderServiceImpl.java, src/test/java/com/jamjam/bookjeok/domains/order/controller/order/PendingOrderControllerTest.java, src/test/java/com/jamjam/bookjeok/domains/order/entity/PendingOrderTest.java, src/test/java/com/jamjam/bookjeok/domains/order/service/pendingorder/PendingOrderServiceImplTest.java
- 주문 요청 시 memberUid, bookId, bookName, price, quantity를 저장하는 DTO 구현
-  validation annotation을 사용해 값을 검증하는 기능 구현
- bookId, bookName으로 도서 테이블에 존재하는 도서 정보인지 확인하는 기능 구현
- PendingOrder 엔티티 안에 orderId를 생성하는 메서드 구현 (orderId : 현재 날짜 + 랜덤 8자리)
- 주문 정보를 pending_orders 테이블에 저장하는 기능 구현
- 클라이언트에 orderId, totalAmount 값을 반환하는 기능 구현
=> [FEATURE] 결제 요청 시 주문 정보를 임시 주문 내역 테이블에 저장하는 기능 구현

src/main/java/com/jamjam/bookjeok/domains/member/controller/AdminController.java, src/main/java/com/jamjam/bookjeok/domains/member/dto/MemberDTO.java, src/main/java/com/jamjam/bookjeok/domains/member/repository/mapper/AdminMapper.java, src/main/java/com/jamjam/bookjeok/domains/member/service/AdminService.java, src/test/java/com/jamjam/bookjeok/domains/member/controller/AdminControllerTest.java, src/test/java/com/jamjam/bookjeok/domains/member/repository/mapper/AdminMapperTest.java, src/test/java/com/jamjam/bookjeok/domains/member/service/AdminServiceTest.java
⭐ 불필요한 import 제거 및 누락된 DTO 추가
✅수정된 부분
- 불필요한 import 제거
- AdminController.java
- AdminMapper.java
- AdminService.java
- AdminControllerTest.java
- AdminMapperTest.java
- AdminServiceTest.java
- MemberDTO 추가
=> [REFACTOR] 불필요한 import  제거 및 누락된 DTO 추가

src/test/java/com/jamjam/bookjeok/domains/member/controller/InterestAuthorControllerTest.java
새로운 더미 데이터에 맞게 InterestAuthorControllerTest 수정
- 관심 작가 삭제하기 테스트
- 멤버의 아이디로 관심 작가 가져오기 테스트
=> [TEST] 새로운 더미 데이터에 맞게 InterestAuthorController 테스트 수정

src/main/java/com/jamjam/bookjeok/domains/member/controller/InterestBookController.java, src/main/java/com/jamjam/bookjeok/domains/member/dto/InterestBookDTO.java, src/main/java/com/jamjam/bookjeok/domains/member/dto/request/InterestBookRequest.java, src/main/java/com/jamjam/bookjeok/domains/member/dto/response/InterestBookListResponse.java, src/main/java/com/jamjam/bookjeok/domains/member/repository/mapper/InterestBookMapper.java, src/main/java/com/jamjam/bookjeok/domains/member/service/InterestBookService.java, src/main/resources/mappers/member/InterestBookMapper.xml, src/test/java/com/jamjam/bookjeok/domains/member/controller/InterestBookControllerTest.java, src/test/java/com/jamjam/bookjeok/domains/member/repository/mapper/InterestBookMapperTest.java, src/test/java/com/jamjam/bookjeok/domains/member/service/InterestBookServiceTest.java
**⭐ 특정 회원의 관심 도서 목록 가져오기**
**✅ 내용**
- `InterestBookController` 작성
- `InterestBookControllerTest` 완료
- 응답 시 `InterestBookListResponse` 객체를 통해 반환하므로 객체 생성
- `InterestBookService` 작성
- `InterestBookService` 완료
- `InterestBookMapper` 작성 
- `InterestBookMapper.java`와 `InterestBookMapper.xml` 파일 작성 완료
- `InterestBookMapperTest` 완료
- `InterestBookDTO` 생성
=> [FEAT] 특정 회원의 관심 도서 목록 가져오기

src/main/resources/application.yml, src/test/resources/application-test.yml
- application.yml에서 tosspayments.api-secret-key 오타 수정
=> [REFACTOR] tosspayments.api-secret-key 오타 수정

src/main/java/com/jamjam/bookjeok/domains/book/controller/BookMemberController.java, src/main/java/com/jamjam/bookjeok/domains/book/dto/BookDetailDTO.java, src/main/java/com/jamjam/bookjeok/domains/book/dto/BookDetailPageDTO.java, src/main/java/com/jamjam/bookjeok/domains/book/dto/PopularBookDTO.java, src/main/java/com/jamjam/bookjeok/domains/book/dto/ReviewDTO.java, src/main/java/com/jamjam/bookjeok/domains/book/dto/request/ReviewRequest.java, src/main/java/com/jamjam/bookjeok/domains/book/dto/response/ReviewResponse.java, src/main/java/com/jamjam/bookjeok/domains/book/entity/Review.java, src/main/java/com/jamjam/bookjeok/domains/book/repository/ReviewRepository.java, src/main/java/com/jamjam/bookjeok/domains/book/repository/mapper/BookMapper.java, src/main/java/com/jamjam/bookjeok/domains/book/service/BookMemberService.java, src/main/java/com/jamjam/bookjeok/domains/book/service/BookMemberServiceImpl.java, src/main/java/com/jamjam/bookjeok/exception/book/BookErrorCode.java, src/main/java/com/jamjam/bookjeok/exception/book/BookExceptionHandler.java, src/main/java/com/jamjam/bookjeok/exception/book/review/InconsistentReviewException.java, src/main/java/com/jamjam/bookjeok/exception/book/review/ReviewNotFoundException.java, src/main/resources/mappers/book/BookMapper.xml, src/test/java/com/jamjam/bookjeok/domains/book/controller/BookMemberControllerTest.java, src/test/java/com/jamjam/bookjeok/domains/book/mapper/BookMapperTest.java, src/test/java/com/jamjam/bookjeok/domains/book/service/BookMemberServiceImplTest.java
**일반회원 도서 조회 및 구매 도서 리뷰 등록, 조회, 수정, 삭제 기능 개발**
✅ 정렬 조건에 따른 도서 목록 조회 및 상세 조회
- 도서 판매량 많은 순  조회
- 관심 도서로 많이 등록된 순 조회
- 최신 등록 순
- 일주일 간 판매량 TOP 10 조회
- ISBN을 통한 도서 상세 조회
✅ 도서 리뷰 비즈니스 로직 처리 
- 구매 도서에 대한 리뷰 작성
- 작성한 리뷰 수정
- 작성한 리뷰 삭제
- 도서별 리뷰 조회
✅ 리뷰 등록/수정/삭제 예외 상황 컨트롤
- InconsistentReviewException
- INCONSISTENT_USER : 리뷰 등록 회원과 수정 회원 불일치
- INCONSISTENT_BOOK : 리뷰 등록 도서와 수정 도서 불일치
- INVALID_WRITER : 리뷰 작성 권한이 없는 유저
- ReviewNotFoundException
- NOT_EXIST_REVIEW : 존재하지 않는 리뷰 요청
✅ 일반회원 도서 조회 및 리뷰 비즈니스 로직 처리 테스트
- BookMemberController
- 컨트롤러 호출을 통한 도서 조회 비즈니스 로직 처리 
- 컨트롤러 호출을 통한 도서 리뷰 비즈니스 로직 처리
- BookMemberServiceImpl
- 정렬 조건 별 도서 조회 비즈니스 로직 처리 
- 예외 상황 컨트롤  
- BookMapper
- keyword 별 / 정렬 조건 별 도서 조회
- 도서 상세 페이지 정보 조회
- 도서 별 리뷰 조회
- 도서 별 저자 조회
- 리뷰 등록, 수정, 삭제, 조회
=> [FEATURE] 일반회원 도서 조회 및 구매 도서 리뷰 등록, 조회, 수정, 삭제 기능 개발

src/main/java/com/jamjam/bookjeok/exception/book/category/BookCategoryNotFoundException.java, src/main/java/com/jamjam/bookjeok/exception/book/category/RegistPreexistingCategoryException.java
✅ exception.book 패키지 하위에 category 패키지로 이동 
- BookCategoryNotFoundException 
- RegistPreexistingCategoryException
=> [REFACTOR] Category Exception 패키지 구조 변경

src/main/java/com/jamjam/bookjeok/domains/book/service/BookAdminServiceImpl.java
- import Exception
- 메소드 `@Transactional` 추가
- 도서 조회 시 작가 정보 누락 추가
=> [REFACTOR] BookAdminServiceImpl 누락된 내용 추가

src/main/java/com/jamjam/bookjeok/domains/member/dto/InterestAuthorDTO.java
`InterestAuthorDTO`에서 `@AllArgsConstructor` 어노테이션 삭제하기
=> [REFACTOR] 필요 없는 import 삭제하기

src/test/java/com/jamjam/bookjeok/domains/member/service/InterestAuthorServiceTest.java
=> [REFACTOR] 필요 없는 import 제거

src/main/java/com/jamjam/bookjeok/domains/book/controller/BookMemberController.java, src/test/java/com/jamjam/bookjeok/domains/book/controller/BookMemberControllerTest.java, src/test/java/com/jamjam/bookjeok/domains/book/service/BookApiServiceImplTest.java
✅ test: 테스트 파라미터 값 변경
- BookApiServiceImplTest : 중복 도서 ISBN 더미 데이터 값으로 변경
- BookMemberControllerTest : 리뷰 등록 파라미터 값 변경
✅fix: 리뷰 등록 시 validCheck 부정 연산자 변경
- BookMemberController : valid check 수정
=> [TEST] 도서 API  Service 및 도서 리뷰 Controller TEST를 위한 코드 수정 

src/test/java/com/jamjam/bookjeok/domains/question/service/QuestionMemberServiceTest.java
✅test: 회원 문의사항 수정 테스트 카테고리 ID값 수정
- QuestionMemberServiceTest : category는 수정할 수 없으므로 파라미터 값 변경
=> [TEST] 회원 문의사항 수정 테스트 카테고리 ID값 수정

src/test/java/com/jamjam/bookjeok/domains/question/controller/QuestionMemberControllerTest.java, src/test/java/com/jamjam/bookjeok/domains/question/service/QuestionMemberServiceTest.java
- QuestionMemberControllerTest 
- questionUid -> questionId로 변경  
- 테스트 데이터 qeustionId 값 변경
- QuestionMemberServiceTest 
- 테스트 데이터 qeustionId 값 변경
=> [TEST] 문의사항 수정 테스트 questionId 값 변경

src/main/java/com/jamjam/bookjeok/domains/payment/dto/BookInventoryDTO.java, src/main/java/com/jamjam/bookjeok/domains/payment/repository/mapper/PaymentMapper.java, src/main/java/com/jamjam/bookjeok/domains/payment/service/PaymentServiceImpl.java, src/main/resources/mappers/payment/Payment.xml
Close: #116 
- 누락된 기능 추가
- 구매할 도서 재고 수량이 충분한 경우 재고 수량을 감소시키는 로직 추가
=> [FEATURE] 구매할 도서 재고 수량이 충분한 경우 재고 수량을 감소시키는 로직 추가

build.gradle, src/main/java/com/jamjam/bookjeok/auth/controller/AuthController.java, src/main/java/com/jamjam/bookjeok/auth/dto/LoginRequest.java, src/main/java/com/jamjam/bookjeok/auth/dto/RefreshTokenRequest.java, src/main/java/com/jamjam/bookjeok/auth/dto/TokenResponse.java, src/main/java/com/jamjam/bookjeok/auth/entity/RefreshToken.java, src/main/java/com/jamjam/bookjeok/auth/repository/RefreshTokenRepository.java, src/main/java/com/jamjam/bookjeok/auth/service/AuthService.java, src/main/java/com/jamjam/bookjeok/auth/service/CustomUserDetailsService.java, src/main/java/com/jamjam/bookjeok/config/SecurityConfig.java, src/main/java/com/jamjam/bookjeok/domains/member/controller/AdminController.java, src/main/java/com/jamjam/bookjeok/domains/member/controller/MemberCommandController.java, src/main/java/com/jamjam/bookjeok/domains/member/controller/MemberQueryController.java, src/main/java/com/jamjam/bookjeok/domains/member/dto/request/MemberCreateRequest.java, src/main/java/com/jamjam/bookjeok/domains/member/entity/Member.java, src/main/java/com/jamjam/bookjeok/domains/member/repository/mapper/MemberMapper.java, src/main/java/com/jamjam/bookjeok/domains/member/service/MemberCommandService.java, src/main/java/com/jamjam/bookjeok/domains/member/service/MemberQueryService.java, src/main/java/com/jamjam/bookjeok/jwt/JwtAuthenticationFilter.java, src/main/java/com/jamjam/bookjeok/jwt/JwtTokenProvider.java, src/main/java/com/jamjam/bookjeok/jwt/RestAccessDeniedHandler.java, src/main/java/com/jamjam/bookjeok/jwt/RestAuthenticationEntryPoint.java, src/main/resources/application.yml, src/main/resources/mappers/member/MemberMapper.xml, src/test/resources/application-test.yml
- 회원가입 기능 구현
- 로그인 기능 구현
- 로그아웃 기능 구현
- 리프레시토큰 재발급 기능 구현
=> [FEATURE] : 회원가입, 로그인, 로그아웃, 리프레시토큰재발급 기능 추가

src/main/java/com/jamjam/bookjeok/domains/cart/controller/CartController.java, src/main/java/com/jamjam/bookjeok/domains/cart/dto/request/CartMemberIdRequest.java, src/main/java/com/jamjam/bookjeok/domains/cart/dto/request/CartRequest.java, src/main/java/com/jamjam/bookjeok/domains/cart/dto/response/CartBookListResponse.java, src/main/java/com/jamjam/bookjeok/domains/cart/dto/response/CartBookResponse.java, src/main/java/com/jamjam/bookjeok/domains/cart/dto/response/CartResponse.java, src/main/java/com/jamjam/bookjeok/domains/cart/entity/Cart.java, src/main/java/com/jamjam/bookjeok/domains/cart/repository/CartRepository.java, src/main/java/com/jamjam/bookjeok/domains/cart/repository/mapper/CartMapper.java, src/main/java/com/jamjam/bookjeok/domains/cart/service/CartService.java, src/main/java/com/jamjam/bookjeok/domains/cart/service/CartServiceImpl.java, src/main/java/com/jamjam/bookjeok/exception/cart/CartBookNotFoundException.java, src/main/java/com/jamjam/bookjeok/exception/cart/CartExceptionHandler.java, src/main/java/com/jamjam/bookjeok/exception/cart/CartItemLimitExceededException.java, src/main/resources/mappers/order/cart/CartMapper.xml, src/test/java/com/jamjam/bookjeok/domains/cart/controller/CartControllerTest.java, src/test/java/com/jamjam/bookjeok/domains/cart/entity/CartTest.java, src/test/java/com/jamjam/bookjeok/domains/cart/service/CartServiceImplTest.java
유지보수를 위해 order 패키지 안에 있던 장바구니 관련 기능들을 별도의 패키지로 이동
=> [REFACTOR] 장바구니 관련 기능들을 order 패키지에서 분리하여 cart 패키지로 이동

src/main/java/com/jamjam/bookjeok/domains/orderdetail/dto/OrderDetailDTO.java, src/main/java/com/jamjam/bookjeok/domains/orderdetail/entity/OrderDetail.java, src/main/java/com/jamjam/bookjeok/domains/orderdetail/repository/OrderDetailRepository.java, src/main/java/com/jamjam/bookjeok/domains/orderdetail/repository/mapper/OrderDetailMapper.java, src/main/java/com/jamjam/bookjeok/domains/orderdetail/service/OrderDetailService.java, src/main/java/com/jamjam/bookjeok/domains/orderdetail/service/OrderDetailServiceImpl.java, src/main/java/com/jamjam/bookjeok/domains/payment/dto/OrderItemsDTO.java, src/main/java/com/jamjam/bookjeok/exception/orderdetail/OrderDetailExceptionHandler.java, src/main/java/com/jamjam/bookjeok/exception/orderdetail/OrderDetailNotFoundException.java, src/main/resources/mappers/order/orderdetail/OrderDetailMapper.xml, src/test/java/com/jamjam/bookjeok/domains/orderdetail/service/OrderDetailServiceImplTest.java
유지보수를 위해 order 패키지 안에 있던 주문 상세 내역 기능들을 별도의 패키지로 이동
=> [REFACTOR] 주문 상세 내역 관련 기능들을 order 패키지에서 분리하여 orderdetail 패키지로 이동
